# Generated by Django 5.0.4 on 2024-04-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_comment_parent_comment_id_alter_story_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
