# Generated by Django 5.0.4 on 2024-04-15 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_story_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
